name: YouTube 24x7 Autobot

on:
  schedule:
    - cron: '0 * * * *' # यह हर 1 घंटे में अपने आप चलेगा
  workflow_dispatch: # इससे तू बटन दबाकर कभी भी मैन्युअल चला सकता है

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Autobot Script
        run: |
          python autobot.py
          
